resolver: lts-7.15

packages:
- '.'

flags: {}

extra-package-dbs: []

extra-deps:
  - digestive-functors-0.8.2.0
  - digestive-functors-lucid-0.0.0.4
  - Spock-digestive-0.3.0.0

nix:
  enable: true
  packages: [curl, postgresql94, zlib]
